### PR TITLE
Styling the Page

### PR DESCRIPTION
**Pull request by Haywhizzz**
In this pull request we have:

-  Added NavBar component and styling
- Added styling to Book and BookList
- Added Form styling
- Added CategoryFilter styling

### CODE REVIEW

**Review by Torres-ssf — CHANGES_REQUESTED** [review]
### Changes required :muscle: 
Hi team :hand: 
Awesome job so far :clap: 
But some changes are required before moving on

- [x] We need to add the live version link to README file.

- [x] We have a bug in the app. Right now is possible to add books without category, since the default value is the category placeholder if you simply fill the book name input and press add, it will create a book without a category and it can't be filtered. The default value for the category select element should be one of the categories values. Or you can specify that the category placeholder it's not a default value inside the element. There are many approaches, but we need to find a way to block books being created with nonsupported categories.

- [x] There is an empty `index.js` file inside `src/containers/` that can be safely deleted

Happy coding :computer: 
**Sérgio Torres**

**Comment by garciajordy** [comment]
# Changes
**Bug:**
- Remove default value.
- Remove empty files.
- Live-link added to Readme file

**Comment by mimipeshy** [comment]
## STATUS: APPROVED 🥳 👯  
Hello @Haywhizzz and @garciajordy 👋🏾 👋🏾 congratulations on making it this far 😄 . 

#### Highlights
- Your deployed app works correctly and the link is included in the README file ✔️ 
- You have worked on all changes requested by the previous TSE ✔️ 

With that, I approve of this project, go ahead and merge 😄 

Regards
__Peris Ndanu __
[GitHub ](https://github.com/mimipeshy)| [LinkedIn ](https://www.linkedin.com/in/peris-ndanu/)| [Twitter](https://twitter.com/pygirl254)

**Comment by garciajordy** [comment]
> ## STATUS: APPROVED 🥳 👯
> Hello @Haywhizzz and @garciajordy 👋🏾 👋🏾 congratulations on making it this far 😄 .
> 
> #### Highlights
> * Your deployed app works correctly and the link is included in the README file ✔️
> * You have worked on all changes requested by the previous TSE ✔️
> 
> With that, I approve of this project, go ahead and merge 😄
> 
> Regards
> __Peris Ndanu __
> [GitHub ](https://github.com/mimipeshy)| [LinkedIn ](https://www.linkedin.com/in/peris-ndanu/)| [Twitter](https://twitter.com/pygirl254)

Could you approve it for microverse?

**Review by mahmoud717 — COMMENTED** [review]
### STATUS: APPROVED ✔️ ✔️ 

**hi @garciajordy  & @Haywhizzz**

**Sorry for the mistake, I'll approve it for ya**

**Pull request merged**
